name: CI
on:
  push:
      branches:
          - "*"
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    name: A job to create pull request against master
    steps:
      - name: Create Pull Request
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "add/"
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_TITLE: "automated pull request"
          PULL_REQUEST_BODY: Automated pull request for $ISSUE_NUMBER"