name: Cron Job for tweeting schedule
on:
  schedule:
    - cron: '*/3 * * * *'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Print hello world
      run: echo "Hello World!!!"
