name: CI
on:
  issues:
    types: ['opened']

jobs:
  parse_issue_create_tweet_file_job:
    runs-on: ubuntu-latest
    name: A job to parse issue and commit into tweets folder
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: parsing from body of the issue
        uses: ./
        id: parse-issue
        with:
          starting-parse-symbol: '<!--::-->'
          file-name-extension: 'tweet'


      # - name: Git commit
      #   env:
      #     ISSUE_NUMBER: ${{ steps.parse-issue.outputs.issueNumber}}
      #   run: |
      #     # git commit if there's any change
      #     if test -n "$(git status --porcelain 2>/dev/null)"; then
      #         git config --global user.email "github.gkarthiks@gmail.com"
      #         git config --global user.name "PR Bot"
      #         git add .
      #         git commit -m "adding tweet file for #$ISSUE_NUMBER"
      #     fi
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Commit changes in new branch
        env:
          ISSUE_NUMBER: ${{ steps.parse-issue.outputs.issueNumber}}
        run: |
          git checkout -b add/#$ISSUE_NUMBER
          git add -A .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'add: new tweet file'
          git push origin add/#$ISSUE_NUMBER

          wget https://github.com/cli/cli/releases/download/v1.0.0/gh_1.0.0_linux_amd64.tar.gz &&  tar -xzf gh_1.0.0_linux_amd64.tar.gz
          gh_1.0.0_linux_amd64/bin/gh -h

          gh_1.0.0_linux_amd64/bin/gh create pr -f

      # - name: Initialize Pull Request
      #   uses: gha-utilities/init-pull-request@v0.2.0
      #   env:
      #     ISSUE_NUMBER: ${{ steps.parse-issue.outputs.issueNumber}}
      #   with:
      #     verbose: true
      #     pull_request_token: ${{ secrets.GITHUB_TOKEN }}
      #     head: add/#$ISSUE_NUMBER
      #     base: master
      #     title: 'add: new tweet file'
      #     body: >
      #       Adding a new tweet file.

      #       Ref: #$ISSUE_NUMBER"
