name: CI
on:
  issues:
    types: ['opened']

jobs:
  parse_issue_create_tweet_file_job:
    runs-on: ubuntu-latest
    name: A job to parse issue and commit into tweets folder
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: parsing from body of the issue
        uses: ./
        id: parse-issue
        with:
          starting-parse-symbol: '<!--::-->'
          file-name-extension: 'tweet'
      # - name: Git commit
      #   env:
      #     ISSUE_NUMBER: ${{ steps.parse-issue.outputs.issueNumber}}
      #   run: |
      #     # git commit if there's any change
      #     if test -n "$(git status --porcelain 2>/dev/null)"; then
      #         git config --global user.email "github.gkarthiks@gmail.com"
      #         git config --global user.name "PR Bot"
      #         git add .
      #         git commit -m "adding tweet file for #$ISSUE_NUMBER"
      #     fi
      - name: Git commit
        env:
          ISSUE_NUMBER: ${{ steps.parse-issue.outputs.issueNumber}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # git commit if there's any change
          if test -n "$(git status --porcelain 2>/dev/null)"; then
              git checkout -b add/#$ISSUE_NUMBER
              API_VERSION=v3;
              BASE=https://api.github.com;
              AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}";
              HEADER="Accept: application/vnd.github.${API_VERSION}+json";
              HEADER="${HEADER}; application/vnd.github.antiope-preview+json; application/vnd.github.shadow-cat-preview+json";

              REPO_URL="${BASE}/repos/${GITHUB_REPOSITORY}";
              PULLS_URL="${REPO_URL}/pulls";

              SOURCE="add/#$ISSUE_NUMBER";  # from this branch
              TARGET="master";  # pull request TO this target
              BODY="this is the content of the message"
              TITLE="new tweet file for #$ISSUE_NUMBER"
              DRAFT="false";   # if PRs are draft

              DATA="{\"title\":\"${TITLE}\", \"body\":\"${BODY}\", \"base\":\"${TARGET}\", \"head\":\"${SOURCE}\", \"draft\":\"${DRAFT}\"}";
              curl -sSL -H "${AUTH_HEADER}" -H "${HEADER}" -X POST --data "${DATA}" ${PULLS_URL};

              # git config --global user.email "github.gkarthiks@gmail.com"
              # git config --global user.name "PR Bot"
              # git add .
              # git commit -m "adding tweet file for #$ISSUE_NUMBER"
          fi

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
