name: Parse and create PR
on:
  issues:
    types: ['opened']
  issue_comment:
    types: ['created']

jobs:
  parse-issue-and-create-pr:
    if: github.event_name != 'issue_comment' || contains(github.event.comment.body, '/validate')
    runs-on: ubuntu-latest
    name: Parse issue, validate timestamp and commit into tweets folder
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: parsing from body of the issue
        uses: ./
        id: parseissue
        with:
          starting-parse-symbol: '<!--::-->'
          file-name-extension: 'tweet'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: echo continue-workflow data
        if: steps.parseissue.outputs.continue-workflow
        run: |
          echo ${{steps.parseissue.outputs.continue-workflow}}
      - name: Create Pull Request
        if: steps.parseissue.outputs.continue-workflow == true
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add new tweet file via automation
          title: 'add: new tweet file via automation'
          body: |
            This PR is auto-generated.
            Ref: #${{ steps.parse-issue.outputs.issueNumber}}
            /cc @${{ github.actor }}
          labels: add, automated pr
          branch: add/${{ steps.parse-issue.outputs.issueNumber}}
          base: master
          signoff: true
          delete-branch: true
