name: CI
on:
  issues:
    types: ['opened']

jobs:
  parse_issue_create_tweet_file_job:
    runs-on: ubuntu-latest
    name: A job to parse issue and commit into tweets folder
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: parsing from body of the issue
        uses: ./
        id: parse-issue
        with:
          starting-parse-symbol: '<!--::-->'
          file-name-extension: 'tweet'
      # - name: Git commit
      #   env:
      #     ISSUE_NUMBER: ${{ steps.parse-issue.outputs.issueNumber}}
      #   run: |
      #     # git commit if there's any change
      #     if test -n "$(git status --porcelain 2>/dev/null)"; then
      #         git config --global user.email "github.gkarthiks@gmail.com"
      #         git config --global user.name "PR Bot"
      #         git add .
      #         git commit -m "adding tweet file for #$ISSUE_NUMBER"
      #     fi
      - name: Update packages
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            echo "nothing to executehere"
          COMMIT_MESSAGE: 'feat: adding tweet file for issue #$ISSUE_NUMBER"'
          COMMIT_NAME: 'GitHub Actions'
          COMMIT_EMAIL: 'github.gkarthiks@gmail.com'
          PR_BRANCH_NAME: 'feat-new-tweet-${PR_ID}'
          PR_TITLE: 'add: new tweet request'

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
